### ISSUE TITLE
Evaluate on custom input

### ISSUE THREAD

**Issue by lakiet1609** [ddsediri/IterativePFN#3]
How to modify a script if I dont have any dataset. I just wanna put custom input (maybe point cloud in xyz format) for your pretrained checkpoint to check whether if that is possible or not

**Comment by ddsediri** [comment]
Hi @lakiet1609, you can use any point cloud inputs, that should be fine. For .xyz files, just specify the folder where you place your .xyz files (see here: https://github.com/ddsediri/IterativePFN/blob/79efe407395b404d6d27550cfe64b2344cfe93c0/test.py#L104)

For other file types, you will need to amend the input_iter function here: https://github.com/ddsediri/IterativePFN/blob/79efe407395b404d6d27550cfe64b2344cfe93c0/test.py#L18

**Comment by lakiet1609** [comment]
How about the setting of dataset_root and dataset ? Will I keep it the same ?. Another thing is that I saw in the test.py script in evaluator part,  is dataset_root necessary for my custom input ?

**Comment by ddsediri** [comment]
Ah yes, so within the input root folder, the script is expecting a folder with the following name format: dataset_resolution_noise. For example: PUNet_10000_poisson_0.01.

So you can change the following:
https://github.com/ddsediri/IterativePFN/blob/79efe407395b404d6d27550cfe64b2344cfe93c0/test.py#L104
https://github.com/ddsediri/IterativePFN/blob/79efe407395b404d6d27550cfe64b2344cfe93c0/test.py#L109
https://github.com/ddsediri/IterativePFN/blob/79efe407395b404d6d27550cfe64b2344cfe93c0/test.py#L110

That should work, just follow that naming convention and place your custom .xyz files in that folder.
