### ISSUE TITLE
Point cloud visualization tools

### ISSUE THREAD

**Issue by YBUZYX** [ddsediri/IterativePFN#5]
Hello dear professor, your paper is excellent. Could you please share with me the point cloud visualization tool you are using?

**Comment by bramburn** [comment]
you can use cloudcompare

**Comment by ddsediri** [comment]
Hi @YBUZYX, @bramburn for this particular paper, I've used Vedo for the visualizations: https://vedo.embl.es/

You can have a look in their documentation on how to visualize point clouds using the point cloud submodule (https://vedo.embl.es/docs/vedo/pointcloud.html) and their plotting functions. I will try to make the visualization code available when I have some time. Cheers!

**Comment by YBUZYX** [comment]
Thank you very much for your help. I used the method you provided, but the color of all the points I visualized is the same. I would like to know, as you wrote in your paper, which parts have good denoising effects and which parts have poor denoising effects, distinguished by color. Below are my results before and after denoising.
![微信图片_20240424215717](https://github.com/ddsediri/IterativePFN/assets/149583665/d5a24ec7-ab54-498c-957b-77fd0a582b7b)
![微信图片_20240424215722](https://github.com/ddsediri/IterativePFN/assets/149583665/538982d4-6875-4e20-b272-c0c9c5dd8882)
![微信图片_20240424215728](https://github.com/ddsediri/IterativePFN/assets/149583665/811aa15e-d7e8-46d9-b9bb-27addb574d4f)

**Comment by ddsediri** [comment]
The color for each point gives the per-point distance to the ground truth mesh. You need to calculate this using the function provided here: https://github.com/ddsediri/IterativePFN/blob/79efe407395b404d6d27550cfe64b2344cfe93c0/models/utils.py#L94

This function gives the distance of each point to the ground truth mesh. You'll have to make sure both the mesh and denoised point clouds are properly normalized first. Once you have the array of per-point P2M distances, you can take these values and convert it to RGB using a LinearSegmentedColormap. Have a look at the function below:

```
from matplotlib.colors import LinearSegmentedColormap

error_max = 0.0005
error_min = 0.0

# create colourmap
cmap_list = ['navy', 'cornflowerblue', 'yellow']
mycmap = LinearSegmentedColormap.from_list('mycmap', cmap_list)

def return_rgba_colors(x):
    return mycmap(np.clip(x, error_min, error_max) / error_max)
```

**Comment by YBUZYX** [comment]
Thank you for your help. Can you provide me with the complete visualization code

**Comment by ddsediri** [comment]
I'm sorry but I need to first clean the code up a bit and I'll make it available afterwards, but not at the moment since I am a bit occupied with other things. 

You should be able to reproduce the visualization fairly easily though, the pointwise P2M code is already in the model/utils.py file. You just need to convert the real numbers to RGB using the mycmap call and then use that for the color array for the point cloud.

**Comment by Yyanming** [comment]
Hello dear professor, your paper is excellent. Could you provide me with the complete visualization code.

**Comment by Yyanming** [comment]
> I'm sorry but I need to first clean the code up a bit and I'll make it available afterwards, but not at the moment since I am a bit occupied with other things.
> 
> You should be able to reproduce the visualization fairly easily though, the pointwise P2M code is already in the model/utils.py file. You just need to convert the real numbers to RGB using the mycmap call and then use that for the color array for the point cloud.

Hello, can you provide me with the complete visual code? I use your function to try, there has been an error, please trouble you.

**Comment by JKK-ja** [comment]
> 您好，亲爱的教授，您的论文非常出色。您能否提供我完整的可视化代码。

您好，请问您现在知道如何可视化这些点云了吗？期待您的回复，谢谢！
